version: '3.4'

services:
  db: #container de MySQL
    image: mysql:5.7.22
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: fabiola
      MYSQL_PASSWORD: secret

  wordpress: #container do WordPress
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: fabiola
      WORDPRESS_DB_PASSWORD: secret
      WORDPRESS_DB_NAME: wordpress